name: agro_tools
description: Agro no bolso

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.2.3"

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  http:
  cupertino_icons: ^1.0.2
  flutter_modular: ^3.1.0
  flutter_mobx: 2.0.0
  mobx: 2.0.0
  modal_bottom_sheet: ^2.0.0
  custom_pop_up_menu: ^1.2.0
  shared_preferences: 2.0.5
  dio: 4.0.0
  nb_utils: 4.2.3
  flutter_svg:
  camera: 0.8.1+7
  weather: ^2.0.0
  geolocator: ^7.0.3
  fluttericon: ^2.0.0
  flutter_html: ^2.0.0
  relative_scale: ^2.0.0
  flutter_quill: ^1.3.3
  flutter_cached_pdfview: ^0.4.0-nullsafety
  flutter_pdfview: ^1.1.0
  flutter_cache_manager: ^3.1.1
  url_launcher: ^6.0.6
  dio_cache_interceptor: ^2.3.1
  location: ^4.2.3
  sqlite3_flutter_libs: ^0.5.0
  banner_carousel: ^1.0.1
  flutter_local_notifications: ^5.0.0+4
  cached_network_image: ^3.0.0
  flutter_easyloading: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0
  share_plus: ^2.1.4
  universal_io: ^2.0.4
  youtube_player_iframe: ^2.2.2
  video_player: ^2.1.12
  youtube_player_flutter: ^8.0.0
  flutter_zoom_drawer: ^2.1.0
  image_picker: ^0.8.3+2
  onesignal_flutter: ^3.2.3
  flutter_rating_bar: ^4.0.0
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.0
  filesystem_picker: ^2.0.0
  table_calendar: ^3.0.3

dev_dependencies:
  flutter_modular_test: 1.0.1
  modular_codegen: 3.0.0
  build_runner: 1.12.2
  mocktail: 0.1.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.1
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo_tcc3.png"

flutter:

  uses-material-design: true
  assets:
    - images/
    - images/cotacao/
    - images/dicas/
    - images/logo.png
    - images/background.jpg
    - images/LikeButton/image/grey.jpg
    - assets/apple_label.txt
    - assets/apple.tflite
    - assets/data.tflite
    - assets/label.txt
  fonts:
    - family: Product Sans
      fonts:
        - asset: fonts/Product Sans Regular.ttf
        - asset: fonts/Product Sans Italic.ttf
        - asset: fonts/Product Sans Bold.ttf
        - asset: fonts/Product Sans Bold Italic.ttf

    - family: Andina
      fonts:
        - asset: fonts/andina.ttf

    - family: Regular
      fonts:
        - asset: fonts/googlesansregular.ttf

    - family: Medium
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/googlesansmedium.ttf

    - family: Bold
      fonts:
        - asset: fonts/googlesansebold.ttf

vars:
  clean: flutter clean
  get: flutter pub get
  runner: flutter pub run build_runner
scripts:
  mobx_build: $clean & $get & $runner build --delete-conflicting-outputs
  mobx_watch: $clean & $get & $runner watch --delete-conflicting-outputs